spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HomeChoreTracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  servlet:
    context-path: /api
security:
  jwt:
    secret-key: 2fc5ee86dd134066d97c6699fa5e087992019ca25a44688dab6b941a4707af30
    expiration-time: 3600000